application:
  id: single
  hash_function: Single
  host: localhost
  union_results: False
  highest_hit: False
  most_interactions: False
  metrics: [ "MAP", "RBO" ]
  partition_port:
    partition:
      5000

salsa:
  walks:
    - 1000
  walk_length:
    - 100
  limit:
    - 10
