dataset:
  should_sample: False
  path: data/left_index.gzip
  sample_size: 500

applications:
  - star-space:
    id: StarSpace
    hash_function: StarSpace
    host: localhost
    merge: False
    show_best_partition: False
    show_partitions: True
    calculate_map_k: True
    partition_port:
      0:
        5000
      1:
        5001
      2:
        5002
      3:
        5003
      4:
        5004
      5:
        5005
      6:
        5006
      7:
        5007
      8:
        5008
      9:
        5009
      10:
        5010
      11:
        5011
      12:
        5012
      13:
        5013
      14:
        5014
      15:
        5015

salsa:
  walks:
    - 100
    - 1000
    - 10000
  walk_length:
    - 100
    - 1000
    - 10000
  limit:
    - 10