dataset:
  should_sample: False
  path: data/left_index.gzip
  sample_size: 500

applications:
  - murmur2:
    id: murmur2
    hash_function: murmur2
    host: localhost
    merge_1: True
    merge_2: True
    merge_3: True
    show_partitions: False
    calculate_map_k: True
    partition_port:
      0:
        5000
      1:
        5001
      2:
        5002
      3:
        5003
      4:
        5004
      5:
        5005
      6:
        5006
      7:
        5007

salsa:
  walks:
    - 100
    - 1000
    - 10000
  walk_length:
    - 100
    - 1000
    - 10000
  limit:
    - 10