application:
  id: StarSpace
  hash_function: StarSpace
  host: localhost
  union_results: True
  highest_hit: True
  most_interactions: True
  show_partitions: False
  metrics: [ "MAP", "RBO" ]
  partition_port:
    0:
      5008
    1:
      5009
    2:
      5010
    3:
      5011
    4:
      5012
    5:
      5013
    6:
      5014
    7:
      5015

salsa:
  walks:
    - 1000
  walk_length:
    - 100
  limit:
    - 10
