dataset:
  should_sample: False
  path: data/left_index.gzip
  sample_size: 500

baseline:
  should_generate_baseline: False

applications:
  - star-space:
    id: StarSpace
    hash_function: StarSpace
    host: localhost
    merge_1: True
    merge_2: True
    merge_3: True
    show_partitions: False
    calculate_map_k: True
    partition_port:
      0:
        5008
      1:
        5009
      2:
        5010
      3:
        5011
      4:
        5012
      5:
        5013
      6:
        5014
      7:
        5015

salsa:
  walks:
    - 1000
  walk_length:
    - 100
  limit:
    - 10
