dataset:
  should_sample: False
  path: data/left_index.gzip
  sample_size: 500

baseline:
  should_generate_baseline: False

applications:
  - murmur2:
    id: murmur2
    hash_function: murmur2
    host: localhost
    merge_1: True
    merge_2: True
    merge_3: True
    show_partitions: False
    calculate_map_k: True
    partition_port:
      0:
        5000
      1:
        5001

salsa:
  walks:
    - 1000
  walk_length:
    - 100
  limit:
    - 10
