application:
  id: StarSpace
  hash_function: StarSpace
  host: localhost
  union_results: True
  highest_hit: True
  most_interactions: True
  show_partitions: True
  metrics: [ "MAP", "RBO" ]
  partition_port:
    0:
      5003
    1:
      5004

salsa:
  walks:
    - 1000
  walk_length:
    - 100
  limit:
    - 10
