dataset:
  should_sample: False
  path: data/left_index.gzip
  sample_size: 500

applications:
  - murmur2:
    id: murmur2
    hash_function: murmur2
    host: localhost
    merge: False
    show_best_partition: False
    show_partitions: True
    calculate_map_k: True
    partition_port:
      0:
        5000
      1:
        5001
      2:
        5002
      3:
        5003

salsa:
  walks:
    - 100
    - 1000
    - 10000
  walk_length:
    - 100
    - 1000
    - 10000
  limit:
    - 10