dataset:
  should_sample: True
  path: data/left_index.gzip
  sample_size: 500

baseline:
  should_generate_baseline: True

applications:

  - single:
    id: single
    hash_function: Single
    host: localhost
    merge_1: False
    merge_2: False
    merge_3: False
    calculate_map_k: False
    partition_port:
      partition:
        5000

salsa:
  walks:
    - 1000
  walk_length:
    - 100
  limit:
    - 10
