dataset:
  should_sample: True
  path: data/left_index.gzip
  sample_size: 500

baseline:
  should_generate_baseline: True
  repeat: 10

application:

  - single:
    id: single
    hash_function: Single
    host: localhost
    union_results: False
    highest_hit: False
    most_interactions: False
    metrics: ["MAP", "RBO"]
    partition_port:
      partition:
        5000

salsa:
  walks:
    - 1000
  walk_length:
    - 100
  limit:
    - 10
