dataset:
  should_sample: True
  path: data/left_index.gzip
  sample_size: 500

applications:
  - baseline:
    id: baseline
    hash_function: Single
    host: localhost
    merge_1: False
    merge_2: False
    merge_3: False
    calculate_map_k: False
    partition_port:
      partition:
        5000

  - single:
    id: single
    hash_function: Single
    host: localhost
    merge_1: False
    merge_2: False
    merge_3: False
    calculate_map_k: False
    partition_port:
      partition:
        5000

salsa:
  walks:
    - 100
    - 1000
    - 10000
  walk_length:
    - 100
    - 1000
    - 10000
  limit:
    - 10