dataset:
  should_sample: False
  path: data/left_index.gzip
  sample_size: 500

baseline:
  should_generate_baseline: False

application:
  - star-space:
    id: StarSpace
    hash_function: StarSpace
    host: localhost
    union_results: True
    highest_hit: True
    most_interactions: True
    show_partitions: False
    metrics: ["MAP", "RBO"]
    partition_port:
      0:
        5004
      1:
        5005
      2:
        5006
      3:
        5007

salsa:
  walks:
    - 1000
  walk_length:
    - 100
  limit:
    - 10
