dataset:
  should_sample: False
  path: data/left_index.gzip
  sample_size: 500

baseline:
  should_generate_baseline: False

applications:
  - star-space:
    id: StarSpace
    hash_function: StarSpace
    host: localhost
    merge_1: True
    merge_2: True
    merge_3: True
    show_partitions: False
    calculate_map_k: True
    partition_port:
      0:
        5004
      1:
        5005
      2:
        5006
      3:
        5007

salsa:
  walks:
    - 1000
  walk_length:
    - 100
  limit:
    - 10
